version: "3"

services:
  database:
    restart: always
    image: mcr.microsoft.com/mssql/server
    container_name: ms-sql-server-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pA55w0rd
    ports:
      - "1433:1433"